server {
    listen 80;
    server_name _;

    root /var/www/public;
    index index.php index.html;

    # Logs visíveis no "Container logs" do Azure
    access_log /dev/stdout;
    error_log  /dev/stderr warn;

    # Healthcheck simples (200 OK)
    location = /healthz {
        access_log off;
        add_header Content-Type text/plain;
        return 200 "OK";
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;           # (ou fastcgi.conf)
        fastcgi_pass 127.0.0.1:9000;      # php-fpm do mesmo container
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_read_timeout 300;
    }

    location ~ /\.ht {
        deny all;
    }
}
